### ISSUE TITLE
ServiceMixin does not obey never_ options

### ISSUE THREAD

**Issue by quulah** [poise/poise-service#49]
https://github.com/poise/poise-service/blob/master/lib/poise_service/service_mixin.rb#L105

vs.

https://github.com/poise/poise-service/blob/master/lib/poise_service/service_providers/base.rb#L72

I ran into this, when trying to abuse poise-service by creating instantiated services with systemd. It now tries to start the <service_name>@.service which causes an error.

I'm separately handling the starting (and stopping, and whatever) of <service_name>@<instance_name>.services.

I tried setting never_start and others to true, but as seen above those aren't checked in the case of the mixin.

**Comment by coderanger** [comment]
ServiceMixin only wraps the underlying `poise_service` resource. While those two bits of code look similar, in the base provider `service_resource` is an instance of `Chef::Resource::Service` while in the mixin it's a `poise_service`. So the first calls the second.

You would have to show your code for me to say what the actual issue is.

**Comment by quulah** [comment]
Thanks. I must have misread the trace yesterday.

It was a matter of properly introducing the never_ options.

Sorry for the noise.
